//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Article3000
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articles
    {
        public string Id { get; set; }
        public string Author { get; set; }
        public string Date { get; set; }
        public string Title { get; set; }
        public string Data { get; set; }
        public string Tags { get; set; }
        public int Num { get; set; }

        public Articles()
        {

        }
        public Articles (Article<string> article)
        {
            var newArticle = new Articles();
            newArticle.Author = article.Author;
            newArticle.Id = article.Id;
            newArticle.Data = article.Data;
            newArticle.Date = article.Date;
            newArticle.Tags = string.Join(" ",article.Tags);
            newArticle.Title = article.Title;
        }
        
    }
}
